curl --user eric.hue@web.de:SecretAmazingPW!1! -X POST -H "Content-Type: application/json" -d "{\"title\":\"SD-Karten\", \"text\":\"Welche maximale Gr\u00f6\u00dfe hat eine k\u00e4uflich erwerbbare (micro)SD-Karte? (Stand: 2025)\", \"options\": [\"256 GB\", \"512 GB\", \"1024 GB\", \"2048 GB\"], \"answer\": [3]}" https://idefix.informatik.htw-dresden.de:8888/api/quizzes
curl --user eric.hue@web.de:SecretAmazingPW!1! -X POST -H "Content-Type: application/json" -d "{\"title\":\"IT-Geschichte\", \"text\":\"Wer gilt als Erfinder des World Wide Web?\", \"options\": [\"Bill Gates\", \"Steve Jobs\", \"Tim Berners-Lee\", \"Linus Torvalds\"], \"answer\": [2]}" https://idefix.informatik.htw-dresden.de:8888/api/quizzes
curl --user eric.hue@web.de:SecretAmazingPW!1! -X POST -H "Content-Type: application/json" -d "{\"title\":\"Raspberry Pi\", \"text\":\"Welche CPU-Architektur verwendet der Raspberry Pi 4?\", \"options\": [\"x86_64\", \"ARMv7-A\", \"ARMv8-A\", \"RISC-V\"], \"answer\": [2]}" https://idefix.informatik.htw-dresden.de:8888/api/quizzes
curl --user eric.hue@web.de:SecretAmazingPW!1! -X POST -H "Content-Type: application/json" -d "{\"title\":\"Physik\", \"text\":\"Wie gro\u00df ist ungef\u00e4hr die Lichtgeschwindigkeit im Vakuum?\", \"options\": [\"300.000 km/s\", \"150.000 km/s\", \"1.000 km/s\", \"30.000 km/s\"], \"answer\": [0]}" https://idefix.informatik.htw-dresden.de:8888/api/quizzes
curl --user eric.hue@web.de:SecretAmazingPW!1! -X POST -H "Content-Type: application/json" -d "{\"title\":\"Prozessoren\", \"text\":\"Welche dieser Prozessorarchitekturen ist typisch f\u00fcr Smartphones?\", \"options\": [\"x86\", \"ARM\", \"RISC-V\", \"SPARC\"], \"answer\": [1]}" https://idefix.informatik.htw-dresden.de:8888/api/quizzes
curl --user eric.hue@web.de:SecretAmazingPW!1! -X POST -H "Content-Type: application/json" -d "{\"title\":\"Geschichte\", \"text\":\"Wann fiel die Berliner Mauer?\", \"options\": [\"1985\", \"1989\", \"1991\", \"1995\"], \"answer\": [1]}" https://idefix.informatik.htw-dresden.de:8888/api/quizzes
curl --user eric.hue@web.de:SecretAmazingPW!1! -X POST -H "Content-Type: application/json" -d "{\"title\":\"Computerhardware\", \"text\":\"Was beschreibt die TDP eines Prozessors?\", \"options\": [\"Die Gr\u00f6\u00dfe des Prozessors\", \"Die Stromspannung\", \"Die K\u00fchlleistung in Watt\", \"Den maximalen Stromverbrauch unter Last\"], \"answer\": [3]}" https://idefix.informatik.htw-dresden.de:8888/api/quizzes
curl --user eric.hue@web.de:SecretAmazingPW!1! -X POST -H "Content-Type: application/json" -d "{\"title\":\"Literatur\", \"text\":\"Wer schrieb den Roman '1984'?\", \"options\": [\"Aldous Huxley\", \"George Orwell\", \"Ray Bradbury\", \"Franz Kafka\"], \"answer\": [1]}" https://idefix.informatik.htw-dresden.de:8888/api/quizzes
curl --user eric.hue@web.de:SecretAmazingPW!1! -X POST -H "Content-Type: application/json" -d "{\"title\":\"Dateisysteme\", \"text\":\"Welches Dateisystem ist auf einem typischen USB-Stick vorformatiert?\", \"options\": [\"NTFS\", \"EXT4\", \"FAT\", \"HFS+\"], \"answer\": [2]}" https://idefix.informatik.htw-dresden.de:8888/api/quizzes
curl --user eric.hue@web.de:SecretAmazingPW!1! -X POST -H "Content-Type: application/json" -d "{\"title\":\"Astronomie\", \"text\":\"Wie viele Planeten hat unser Sonnensystem? (Stand: 2025)\", \"options\": [\"8\", \"9\", \"10\", \"7\"], \"answer\": [0]}" https://idefix.informatik.htw-dresden.de:8888/api/quizzes
curl --user eric.hue@web.de:SecretAmazingPW!1! -X POST -H "Content-Type: application/json" -d "{\"title\":\"Physik\", \"text\":\"Warum erscheint der Himmel tags\u00fcber blau?\", \"options\": [\"Weil die Atmosph\u00e4re das blaue Licht st\u00e4rker streut als andere Farben\", \"Weil Wasserteilchen in der Luft blaues Licht reflektieren\", \"Weil das Sonnenlicht selbst blau ist\", \"Weil das menschliche Auge blau bevorzugt\"], \"answer\": [0]}" https://idefix.informatik.htw-dresden.de:8888/api/quizzes

pause